name: multi_llm_api
description: Um gateway unificado para múltiplos modelos de linguagem (LLMs) construído com Dart.
version: 1.0.0
# repository: https://github.com/seu-usuario/multi-llm-api

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dotenv: ^4.2.0
  get_it: ^7.6.7
  google_generative_ai: ^0.4.6
  json_annotation: ^4.8.1
  logging: ^1.2.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_static: ^1.1.3
  shelf_swagger_ui: ^2.0.0

  meta: any
  postgres: ^3.5.6
  dart_jsonwebtoken: ^3.2.0
  jwt_decoder: ^2.0.1
  uuid: ^4.3.3
  http: ^1.4.0
  crypto: ^3.0.6
  
dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  lints: ^3.0.0
  swagger_dart_code_generator: ^3.0.1 # Target latest attempted version
  test: ^1.24.0
  very_good_analysis: ^5.1.0
  coverage: ^1.7.2
