// This is a placeholder file to demonstrate the structure of the generated API code.
// The actual code would be generated by the swagger_dart_code_generator package.

library multi_llm_api;

export 'api.dart';
export 'models.dart';

/// API Dart client library.
///
/// This library provides a client for the API Dart Example API.
/// It includes models for requests and responses, as well as a client
/// for making API requests.
///
/// Example usage:
///
/// ```dart
/// import 'package:multi_llm_api/generated_api/multi_llm_api.dart';
///
/// void main() async {
///   final client = ApiClient(baseUrl: 'http://localhost:8081/api/v1');
///
///   // Authenticate
///   final loginResponse = await client.authLogin(
///     loginRequest: LoginRequest(username: 'user', password: 'password'),
///   );
///
///   // Set the auth token for subsequent requests
///   client.setBearerAuth(loginResponse.token);
///
///   // Make authenticated requests
///   final items = await client.itemsGet();
///   print(items);
/// }
