/// {@template generate_text_response_dto}
/// Data Transfer Object for the text generation response.
/// {@endtemplate}
class GenerateTextResponseDto {
  /// {@macro generate_text_response_dto}
  GenerateTextResponseDto({required this.generatedText});

  /// The text generated by the AI model.
  final String generatedText;

  /// Converts the DTO to a JSON encodable Map.
  Map<String, dynamic> toJson() {
    return {
      'generated_text': generatedText,
    };
  }
}
